export const CHANGE_STATUS_FETCHING = "CHANGE_STATUS_FETCHING";
export const CHANGE_STATUS_FULFILLED = "CHANGE_STATUS_FULFILLED";
export const SET_ERROR = "SET_ERROR";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_KCAL = "SET_USER_KCAL";
export const SET_ALL_USER_KCAL = "SET_ALL_USER_KCAL";
export const SHOW_ALL_USER_KCAL = "SHOW_ALL_USER_KCAL";
export const SHOW_USER_KCAL = "SHOW_USER_KCAL";
export const SEND_MESSAGE = "SEND_MESSAGE";

